const POT = 35;

Graphics.prototype.setFontOpenSansCondensed = function() {
  // Actual height 16 (15 - 0)
  // 1 BPP
  return this.setFontCustom(
    atob('AAAAAAAAAAAAAP9w/3D/cAAA4ADwAPAA4ADwAPAA8AAAABnwP/D/8P/w//D/8P+AGYAQAAAAGHB+cH4w//z//Gfwc/AAAHwA/gD+EP5w//A/4H/A//D38IfwB/AH4AAAAeB/8P/w/zD/8P/w+/AD8APwAADgAPAA8ADgAAAAH/B//P/+8B6AAgAAgALgDv/+//4/+AAAMAB8ALwA/AD8APwAfAAAAAMAAwAf4B/gH8ADAAIAAAAAPAA8ADgAAAGAAYABgAGAAYAAAAAAAHAAcABwAAAAMAHwD/A/4P8A+AAAAH/g//D/8OBw//D/8H/gAAAwAHAA8AD/8P/w//AAAEAw4PDh8Mfw/7D/MH4wAABAcORw5jDOMP/w//B74AAAB8AfwP7A//D/8P/wAMAAAABw/HD8MPwwz/DP8M/gAAA/4H/w//DucM/wz/AHwAAAwADAcMPw3/D/4P4A8AAAADDAf/D/8P/w//D/8P/wAAB+AP8w/zDjcP/w/+B/wAAAAAAccBxwHHAAABw8HDwcOAgAAAAHAAcAD4AdwB3AOOAQQAAADYANgA2ADYANgA2ACIAAABBAOOAdwB3AD4AHAAcAAADgAONwz3D/cP4geAAAAB/AP/B/+O/439jf2N/Y39j/2H/AP8AGAAAAB/B/8P/g/YD/gP/wH/AB8AAQAAAAAP/w//D/8MYw//D/8HvgAAA/wH/g//Dw8MAw4DDgcAAAAAD/8P/w//DAMPDw//B/4D/AAAD/8P/w//DGMMYwxjAAAP/w//D/8MYAxgDGAAAAP8B/4P/w5nDGMMfw5/DH8AAA//D/8P/wBgAGAP/w//D/8AAAAAD/8P/w//AAAP/+//7//AAAAAD/8P/w//A/gP/w//Dg8AAAAAD/8P/w//AAMAAwAAAAAP/w//D/8P/gf/AD8D/w//D/8P/w//D/8AAA//D/8P/w/gA/wA/w//D/8P/wAAA/wH/g//Dw8MAw4HD/8H/gP8AAAP/w//D/8MMA/wD/AH4AAAA/wH/g//Dw8MA44H7//n/+P8YAAAAA//D/8P/wz8D/8P/wfPAAAHxw/jD/MM/w5/DD4AAAwADAAP/w//D/8MAAwAAAAP/g//D/8ABwAHD/8P/w/+AAAP8A//B/8APwf/D/8P8A4AAAAP+A//B/8B/w//D/gP/g//AH8P/w//D+AIAAAADw8P/w//B/wP/w+fDgcAAQAADwAPwA//A/8P/w/gDwAIAAAADB8Mfw3/D/sPww8DDAMAAAAAD//v/+//7ABgAAwAD4AP8Af8AP8AHwAADABv/+//7//gAADwA/AP4A8AD8AD8ADwADAAAAAAIAAgACAAIAAgAAAAAAAMAA4ADgAOAAIAAAAAHwG/Ab8BswH/Af8A/wAAD/+P/4//gMGA/4D/gH8AHAAAAP4B/wH/AYMBgwGDAAAAfwD/gP+AwY//j/+P/4AAAHwA/gH/Af8B+wH7AfsAAADAB/+P/4//jMAAAABg4f/x//H/Mfsx+/Hz8AAP/4//j/+AwAD/gP+A/4AfgAAM/47/jP+AAAz//v/8//AAD/+P/4//gH4A/4DvgMOAAIAAD/+P/4//gAAB/wH/Af8B/wGAAf8B/wH/AcAB/wH/Af8AAAH/Af8B/wGAAf8B/wH/AD8AAAB4AP4B/wH/AYMB/wH/AP4AAAH/8f/x//GDAf8B/wD+ADgAAAD+Af8B/wGDAf/x//H/8AAB/wH/Af8BwAGAAAAA4wHzAfsBvwGfAY4AAAGAB/8H/wf/AYMAAAH/Af8B/wADAf8B/wH/Af8AAAH8Af8A/wD/Af8B/AHAAAAB/gH/Af8B/wH/AfwB/wD/Af8B/wH4AAABgwHvAf8A/gH/Ae8BgwAAAfAx/nH/8D/x/8H+AeAAAAGPAf8B/wH7AeMBAwAAADgAOAf/z//v7+wAYAAAAAAAD//////////wAA/H7+/v/+f/wDgAEAAAAHAAcABgAHAAMAAwAHAAAA'),
    32,
    atob("BAUICggNCgUGBggIBAYFBwgHCAgICAgICAgFBQgICAcNCgkICgcHCQkFBAkHDgoKCAoJBwgJCQ4JCQgGBwUJBggICQcICAYICQQECQQNCQkJCAYHBgkIDAgIBwcHBwg="),
    16|65536
  );
}


// 128x64
const velocimetro = atob("gEABAAAAAAAAH/+AAAAAAAAAAAAAAAAAAf//+AAAAAAAAAAAAAAAAAf///4AAAAAAAAAAAAAAAAf4AB/gAAAAAAAAAAAAAAAfg//B+AAAAAAAAAAAAAAAfh//+H4AAAAAAAAAAAAAAPj///8fAAAAAAAAAAAAAAHz/Bg/z4AAAAAAAAAAAAADx+AYB+PAAAAAAAAAAAAAB5+AGAH54AAAAAAAAAAAAA8/gBgB/PAAAAAAAAAAAAAeecAYA554AAAAAAAAAAAAPPGAGAGPPAAAAAAAAAAAAHngAAAAB5wAAAAAAAAAAABzwAAAAAPOAAAAAAAAAAAA94AAAAAB5wAAAAAAAAAAAOcAAAAAAOcAAAAAAAAAAAHOAAAAAABzgAAAAAAAAAAB3gAAAAAAe4AAAAAAAAAAA5+AAAAAAfnAAAAAAAAAAAO/gAAAAAH9wAAAAAAAAAAHOQAAAAAAnOAAAAAAAAAABzgAAAAAABzgAAAAAAAAAAdwAAAAAAAO4AAAAAAAAAAHcAAAAAAADuAAAAAAAAAADnAAAAAAAA5wAAAAAAAAAA7gAAAAAAAHcAAAAAAAAAAO4AAAGAAAB3AAAAAAAAAADuAAAH4AAAdwAAAAAAAAAA7gAAD/AAAHcAAAAAAAAAAO4AAA/wAAB3AAAAAAAAAADv+AAf+AAf9wAAAAAAAAAA7/gAH/gAH/cAAAAAAAAAAO4AAA/wAAB3AAAAAAAAAADuAAAP8AAAdwAAAAAAAAAA7gAAB+AAAHcAAAAAAAAAAO4AAAGAAAB3AAAAAAAAAADuAAAAAAAAdwAAAAAAAAAA5wAAAAAAAOcAAAAAAAAAAHcAAAAAAADuAAAAAAAAAAB3AAAAAAAA7gAAAAAAAAAAc4AAAAAAAc4AAAAAAAAAAHOAAAAAAAHOAAAAAAAAAAA7+AAAAAAf3AAAAAAAAAAAOfgD///AH5wAAAAAAAAADh3gD///8Ae4cccAAAAAABEc4A////AHOIoogAAAAAARDnAO7ndwDnAKKIAAAAAAEQ54Du53cB7wCiiAAAAAABEHPA7ud3A84BIogAAAAAARA54P///wecAiKIAAAAAAEQPPD///8PPAQiiAAAAAAA4B54P//8HngPnHAAAAAAAAAPPgAAAHzwAAAAAAAAAAAAB5+AAAH54AAAAAAAAAAAAAPH4AAH48AAAAAAAAAAAAAB8/wAP8+AAAAAAAAAAAAAAPj///8fAAAAAAAAAAAAAAA+H//4fAAAAAAAAAAAAAAAH4P/wfgAAAAAAAAAAAAAAAf4AB/gAAAAAAAAAAAAAAAB////gAAAAAAAAAAAAAAAAH///gAAAAAAAAAAAAAAAAAH/+AAAAAAAAAAA==");

I2C1.setup();
let oled = require("SSD1306").connect(I2C1);

setInterval(function(){
    let valorPot = analogRead(POT);
    let ang = Math.round(240 * valorPot - 210);
    let rad = ang * Math.PI / 180;
    let veloc = Math.round(200 * valorPot);
    let x = 20 * Math.cos(rad) + 58;
    let y = 20 * Math.sin(rad) + 32;

    console.log("Velocidade: " + veloc.toFixed(0))
    console.log("Angulo: " + ang.toFixed(0))

    oled.clear();
    oled.drawImage(velocimetro, 0 ,0);
    oled.drawLine(58, 32, x, y)
    oled.setFontOpenSansCondensed();
    oled.drawString("V: ", 0, 0)
    oled.drawString(veloc.toFixed(0), 0, 24)

    oled.flip();
}, 100)

