const mimico = {
  width : 64, height : 64, bpp : 1,
  buffer : atob("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD/////8AAAA///////AAAD///////wAAPAAAAAH/gAAwAAAH4B/AAAAAAD/4AeAAAAAAf/wA8AAAAAD+PgB4AAAAAfGPADgAAAAB48eAPAAH///////+AB////////4AP////////gA8BwAGAcAgADwFwA+BYCAANARgCMEwYAAEDDAQYxhIAAYNmDAybNwAAgnM45r2lAADG2eGzJu0AAEyMQxhjyQAAeYYGDEGJAAwxAwwGQNkADgMBGANAcYAPxgGwAcAwgA/8AOAAgDCAD////////4AMf///////gAwf//////+ADBwAOPHAA4AMHAA48cADgAwcADjxwAOADBwAOPHAA4AMHAA4c8ADgAwcADwHwAOADBwAHg/AA4AMHAAPH4ADgAwcAAefAAOADBwAA/4AA4AMHAAB/AADgAwcAAD4AAOADBwAAHgAA4AMHAAAAAADgAwcAAAAAAOAA=")
}

I2C1.setup()
let oled = require("SSD1306").connect(I2C1)

oled.clear()
oled.drawImage(mimico, 32, 0)
oled.flip();