const bau_1 = {
  width : 64, height : 64, bpp : 1,
  buffer : atob("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD/////8AAAA///////AAAD///////wAAPAAAAAH/gAAwAAAH4B/AAAAAAD/4AeAAAAAAf/wA8AAAAAD+PgB4AAAAAfGPADgAAAAB48eAPAAH///////+AB////////4AP////////gA8BwAGAcAgADwFwA+BYCAANARgCMEwYAAEDDAQYxhIAAYNmDAybNwAAgnM45r2lAADG2eGzJu0AAEyMQxhjyQAAeYYGDEGJAAwxAwwGQNkADgMBGANAcYAPxgGwAcAwgA/8AOAAgDCAD////////4AMf///////gAwf//////+ADBwAOPHAA4AMHAA48cADgAwcADjxwAOADBwAOPHAA4AMHAA4c8ADgAwcADwHwAOADBwAHg/AA4AMHAAPH4ADgAwcAAefAAOADBwAA/4AA4AMHAAB/AADgAwcAAD4AAOADBwAAHgAA4AMHAAAAAADgAwcAAAAAAOAA=")
}

const bau_2 = {
  width : 64, height : 64, bpp : 1,
  buffer : atob("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD/////8AAAA///////AAAD///////wAAPAAAAAH/gAAwAAAH4B/AAAAAAD/4AeAAAAAAf/wA8AAAAAD+PgB4AAAAAfGPADgAAAAB48eAPAAH///////+AB////////4AP////////gA4gHABgDwEADiB2AdAxggAMEMMDGGDGAAARnYZsx02AABt07Oeda4AADsI7szEygAwNgQYQ4bSADgIBjBmAjEAP5gDwCwDYQA/8AGAGAHBAD////////8AMf///////wAwf//////+ADBwAOPHAA4AMHAA48cADgAwcADjxwAOADBwAOPHAA4AMHAA4c8ADgAwcADwHwAOADBwAHg/AA4AMHAAPH4ADgAwcAAefAAOADBwAA/4AA4AMHAAB/AADgAwcAAD4AAOADBwAAHgAA4AMHAAAAAADgAwcAAAAAAOAA=")
}

const bau_3 = {
  width : 64, height : 64, bpp : 1,
  buffer : atob("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD/////8AAAA///////AAAD///////wAAPAAAAAH/gAAwAAAH4B/AAAAAAD/4AeAAAAAAf/wA8AAAAAD+PgB4AAAAAfGPADgAAAAB48eAPAAH///////+AB////////4AP////////gA+BwMB4AYOADsNBwEwHwoAMRmNghgxGgAxsJjECOEyADjgkEwNgKIAPmDgeAcA4gA/4GAwAgDCAD////////4AMf///////gAwf//////+ADBwAOPHAA4AMHAA48cADgAwcADjxwAOADBwAOPHAA4AMHAA4c8ADgAwcADwHwAOADBwAHg/AA4AMHAAPH4ADgAwcAAefAAOADBwAA/4AA4AMHAAB/AADgAwcAAD4AAOADBwAAHgAA4AMHAAAAAADgAwcAAAAAAOAA=")
}


const bau_4 = {
  width : 64, height : 64, bpp : 1,
  buffer : atob("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP/////wAAAD//////8AAAP///////AAA8AAAAAf+AADAAAAfgH8AAAAAAP/gB4AAAAAB//ADwAAAAAP4+AHgAAAAB8Y8AOAAAAAHjx4A8AAf///////4AH////////gA////////+ADmOwNgHh2IAONhniAzMMgA/cDwPsFgSAD////////4AMf///////gAwf//////+ADBwAOPHAA4AMHAA48cADgAwcADjxwAOADBwAOPHAA4AMHAA4c8ADgAwcADwHwAOADBwAHg/AA4AMHAAPH4ADgAwcAAefAAOADBwAA/4AA4AMHAAB/AADgAwcAAD4AAOADBwAAHgAA4AMHAAAAAADgAwcAAAAAAOAA=")
}
const bau_5 = {
  width : 64, height : 64, bpp : 1,
  buffer : atob("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD/////8AAAA///////AAAD///////wAAPAAAAAH/gAAwAAAH4B/AAAAAAD/4AeAAAAAAf/wA8AAAAAD+PgB4AAAAAfGPADgAAAAB48eAPAAH///////+AB////////4AP////////gA/H8D8B4HmAD////////4AMf///////gAwf//////+ADBwAOPHAA4AMHAA48cADgAwcADjxwAOADBwAOPHAA4AMHAA4c8ADgAwcADwHwAOADBwAHg/AA4AMHAAPH4ADgAwcAAefAAOADBwAA/4AA4AMHAAB/AADgAwcAAD4AAOADBwAAHgAA4AMHAAAAAADgAwcAAAAAAOAA=")
}

const bau_6 = {
  width : 64, height : 64, bpp : 1,
  buffer : atob("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD/////8AAAA///////AAAD///////wAAPAAAAAH/gAAwAAAH4B/AAAAAAD/4AeAAAAAAf/wA8AAAAAD+PgB4AAAAAfGPADgAAAAB48eAPAAH///////+AB////////4AP////////gAwf//////+ADBwAOPHAA4AMHAA48cADgAwcADjxwAOADBwAOPHAA4AMHAA4c8ADgAwcADwHwAOADBwAHg/AA4AMHAAPH4ADgAwcAAefAAOADBwAA/4AA4AMHAAB/AADgAwcAAD4AAOADBwAAHgAA4AMHAAAAAADgAwcAAAAAAOAA=")
}


let stick_index = 0;
const stick_mov =
[
    bau_1,
    bau_2,
    bau_3,
    bau_4,
    bau_5,
    bau_6,
    bau_5,
    bau_4,
    bau_3,
    bau_2
];

I2C1.setup();
let oled = require("SSD1306").connect(I2C1);

setInterval(function()
{
    oled.clear();
    oled.drawImage(stick_mov[stick_index], 32, 0);
    oled.flip();

    stick_index = (stick_index + 1)%stick_mov.length;
}, 30);